[versions]
androidGradlePlugin = "9.0.1"
activity = "1.13.0"
camerax = "1.6.2"
mlkitLabeling = "17.0.9"
junit = "4.13.2"

[libraries]
androidx-activity = { module = "androidx.activity:activity", version.ref = "activity" }
camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camerax" }
camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camerax" }
camera-view = { module = "androidx.camera:camera-view", version.ref = "camerax" }
mlkit-image-labeling = { module = "com.google.mlkit:image-labeling", version.ref = "mlkitLabeling" }
junit = { module = "junit:junit", version.ref = "junit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
