"""Writes the Repeat after Rin recording protocols (task 3.5): app/src/debug/assets/repeat-lab/{dev,heldout}.json.

Run once, then commit; the files are frozen before any recording (docs/spikes/3.5-repeat-after-rin.md). Deterministic,
so rerunning it must leave them unchanged:
  python tools/stt/make-protocol.py

Each set has 40 tries. 24 "say": the user says the target sentence (12 phone in hand, 8 lying down with a sleepy voice,
4 with the phone about 1 m away). 16 negatives, which must NOT pass: 6 "mumble" (sleepy sounds, no words), 6 "other"
(another sentence of the pool, the one sharing most words with the target), 4 "partial" (only the first half of the
target). Dev uses R01-R12, held-out R13-R30, so the rules are also checked on sentences they were not tuned on.
"""
import json
import random
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
POOL = json.loads((ROOT / "app/src/main/assets/repeat/sentences.json").read_text(encoding="utf-8"))["sentences"]
OUT = ROOT / "app/src/debug/assets/repeat-lab"


def words(text):
    return [w.strip(",.!?;:\"").lower() for w in text.split(" ") if w.strip(",.!?;:\"")]


def build(name, ids, seed):
    rng = random.Random(seed)
    by_id = {s["id"]: s for s in POOL}
    targets = [by_id[i] for i in ids]
    # 24 says: every target once, then repeats from the start, until 24.
    says = [targets[i % len(targets)] for i in range(24)]
    conds = ["hand"] * 12 + ["lying"] * 8 + ["far"] * 4
    rng.shuffle(conds)
    items = [{"kind": "say", "target": s["id"], "read": s["text"], "cond": c} for s, c in zip(says, conds)]
    # 16 negative targets: a shuffled pass over the targets, repeated as needed (dev has only 12).
    shuffled = rng.sample(targets, len(targets))
    neg_targets = [shuffled[i % len(shuffled)] for i in range(16)]
    for s in neg_targets[:6]:
        items.append({"kind": "mumble", "target": s["id"], "read": "", "cond": rng.choice(["hand", "lying"])})
    for s in neg_targets[6:12]:
        # The other sentence (from the whole pool) sharing the most words with the target: the hardest to reject.
        others = [o for o in POOL if o["id"] != s["id"]]
        other = max(others, key=lambda o: (len(set(words(o["text"])) & set(words(s["text"]))), o["id"]))
        items.append({"kind": "other", "target": s["id"], "read": other["text"], "cond": rng.choice(["hand", "lying"])})
    for s in neg_targets[12:16]:
        tokens = s["text"].split(" ")
        items.append({"kind": "partial", "target": s["id"], "read": " ".join(tokens[: len(tokens) // 2]), "cond": "hand"})
    rng.shuffle(items)
    for n, item in enumerate(items, 1):
        item["id"] = f"{name[0]}{n:02d}"
    OUT.mkdir(parents=True, exist_ok=True)
    doc = {
        "_note": f"Repeat after Rin recording protocol '{name}' (task 3.5), frozen before any recording. "
        "Generated by tools/stt/make-protocol.py; never edit by hand.",
        "items": [{k: item[k] for k in ("id", "kind", "target", "cond", "read")} for item in items],
    }
    # LF on every OS, so a rerun leaves the committed files byte for byte the same.
    with open(OUT / f"{name}.json", "w", encoding="utf-8", newline="\n") as f:
        f.write(json.dumps(doc, indent=1, ensure_ascii=False) + "\n")
    kinds = {k: sum(1 for i in items if i["kind"] == k) for k in ("say", "mumble", "other", "partial")}
    print(name, kinds)


build("dev", [f"R{i:02d}" for i in range(1, 13)], seed=35)
build("heldout", [f"R{i:02d}" for i in range(13, 31)], seed=36)
